/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotecaprogra3;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author ph
 */
public class VentanaRegistrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaRegistrar
     */
    private VentanaPrincipal vtPrincipal;

    public void setVtPrincipal(VentanaPrincipal vtPrincipal) {
        this.vtPrincipal = vtPrincipal;
    }
    
    private ImageIcon icono=new ImageIcon("imagenesDeFormularios/loginUsers.png");
    public VentanaRegistrar() {
       
        initComponents();
        //esta linewa indica que la ventana no se puede modificar de tamanio
        this.setResizable(false);
        //esta linea indica que la ventana debe tener un boton para cerrar.-
        this.setClosable(true);
        //se le asigna al boton de cerrar la opcion de cerrar la ventana
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       this.setIconifiable(true);
        this.setTitle(" Iniciar Sesion ");
      this.setFrameIcon(icono);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        JbtnCerrar = new javax.swing.JButton();
        JbtnRegistrar = new javax.swing.JButton();
        JlbUsuario = new javax.swing.JLabel();
        JtxtUsuario = new javax.swing.JTextField();
        JlbContrasenia = new javax.swing.JLabel();
        JtxtContrasenia = new javax.swing.JPasswordField();
        JlblImagen = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JbtnCerrar.setText("Cerrar");
        JbtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnCerrarActionPerformed(evt);
            }
        });

        JbtnRegistrar.setText("Registrar");
        JbtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnRegistrarActionPerformed(evt);
            }
        });

        JlbUsuario.setText("Id Usuario: ");

        JtxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtUsuarioActionPerformed(evt);
            }
        });

        JlbContrasenia.setText("Contraseña: ");

        JtxtContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtContraseniaActionPerformed(evt);
            }
        });

        JlblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesGrandes/login1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JbtnRegistrar)
                                .addGap(18, 18, 18)
                                .addComponent(JbtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JlbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JlbContrasenia))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JtxtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JlblImagen)
                        .addGap(105, 105, 105))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JlblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlbUsuario)
                    .addComponent(JtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlbContrasenia)
                    .addComponent(JtxtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnCerrar)
                    .addComponent(JbtnRegistrar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtxtContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtContraseniaActionPerformed

    private void JtxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtUsuarioActionPerformed

    private void JbtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnRegistrarActionPerformed
        // TODO add your handling code here:
        String tipoUsuario=JtxtUsuario.getText();
        
        if(tipoUsuario.equalsIgnoreCase("administrador")){
            this.vtPrincipal.desbloquer(1);
        }else if(tipoUsuario.equalsIgnoreCase("Encargado")){
            this.vtPrincipal.desbloquer(2);
        }else{
            JOptionPane.showMessageDialog(null, "Error en el tipo de usuario introducido..\n"
                    + "intentelo de nuevo.");
        }
        this.doDefaultCloseAction();
        
    }//GEN-LAST:event_JbtnRegistrarActionPerformed

    private void JbtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.doDefaultCloseAction();
        
    }//GEN-LAST:event_JbtnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new VentanaRegistrar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnCerrar;
    private javax.swing.JButton JbtnRegistrar;
    private javax.swing.JLabel JlbContrasenia;
    private javax.swing.JLabel JlbUsuario;
    private javax.swing.JLabel JlblImagen;
    private javax.swing.JPasswordField JtxtContrasenia;
    private javax.swing.JTextField JtxtUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
