/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotecaprogra3;

import LogicaDeClases.AdministradorDatos;
import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author ph
 */
public class ventanaDarDeAlta_Baja extends javax.swing.JInternalFrame {
AdministradorDatos admin=new AdministradorDatos();
    /**
     * Creates new form ventanaDarDeAlta_Baja
     */
     private ImageIcon icono=new ImageIcon("imagenesDeFormularios/dar de alta o baja.png");
    public ventanaDarDeAlta_Baja() {
        initComponents();
        this.setClosable(true);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setTitle(" Dar de Alta o Baja ");
        this.setIconifiable(true);
        this.setFrameIcon(icono);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JlblImagen = new javax.swing.JLabel();
        JtxtCarnet = new javax.swing.JTextField();
        JtxtEstadoEstudiante = new javax.swing.JTextField();
        JlblCarnet = new javax.swing.JLabel();
        JlblEstadoEstudiante = new javax.swing.JLabel();
        JlblNuevoEstado = new javax.swing.JLabel();
        JcomboNuevoEstado = new javax.swing.JComboBox();
        JlblNombres = new javax.swing.JLabel();
        JtxtNombres = new javax.swing.JTextField();
        JlblAppellidos = new javax.swing.JLabel();
        JtxtApellidos = new javax.swing.JTextField();
        JbtnGuardar = new javax.swing.JButton();
        JbtnSalir = new javax.swing.JButton();
        JlblMotivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtextAMotivoDeCambio = new javax.swing.JTextArea();
        JbtnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JlblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesGrandes/unlock.png"))); // NOI18N

        JtxtEstadoEstudiante.setEditable(false);

        JlblCarnet.setText("Carnet: ");

        JlblEstadoEstudiante.setText("Estado Actual Estudiante: ");

        JlblNuevoEstado.setText("Nuevo Estado:");

        JcomboNuevoEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Alta", "Baja" }));

        JlblNombres.setText("Nombres: ");

        JtxtNombres.setEditable(false);

        JlblAppellidos.setText("Apellidos: ");

        JtxtApellidos.setEditable(false);

        JbtnGuardar.setText("Guardar Cambios");
        JbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnGuardarActionPerformed(evt);
            }
        });

        JbtnSalir.setText("Salir");
        JbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnSalirActionPerformed(evt);
            }
        });

        JlblMotivo.setText("Motivo de cambio De Estado: ");

        JtextAMotivoDeCambio.setColumns(20);
        JtextAMotivoDeCambio.setRows(5);
        jScrollPane1.setViewportView(JtextAMotivoDeCambio);

        JbtnBuscar.setText("Buscar");
        JbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JlblImagen)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JlblCarnet)
                            .addComponent(JlblNuevoEstado)
                            .addComponent(JlblNombres)
                            .addComponent(JlblAppellidos)
                            .addComponent(JbtnGuardar)
                            .addComponent(JlblMotivo)
                            .addComponent(JlblEstadoEstudiante))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JtxtApellidos)
                            .addComponent(JtxtCarnet)
                            .addComponent(JtxtNombres, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                .addComponent(JbtnSalir)
                                .addGap(68, 68, 68))
                            .addComponent(JtxtEstadoEstudiante, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JbtnBuscar)
                                    .addComponent(JcomboNuevoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(JlblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtxtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlblCarnet))
                .addGap(18, 18, 18)
                .addComponent(JbtnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlblNombres)
                    .addComponent(JtxtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlblAppellidos)
                    .addComponent(JtxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlblEstadoEstudiante)
                    .addComponent(JtxtEstadoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlblNuevoEstado)
                    .addComponent(JcomboNuevoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JlblMotivo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnGuardar)
                    .addComponent(JbtnSalir))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnSalirActionPerformed
        // TODO add your handling code here:
        this.doDefaultCloseAction();
    }//GEN-LAST:event_JbtnSalirActionPerformed

    private void JbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuscarActionPerformed
        // TODO add your handling code here:
        
      ResultSet resultadoBusqueda=  admin.buscarEstudiante(JtxtCarnet.getText());
      
      ResultSet resultadoBusquedaEstado=admin.buscarEstadoEstudiante(this.JtxtCarnet.getText());
        try {
            while(resultadoBusqueda.next()){
            JtxtApellidos.setText(resultadoBusqueda.getString("apellido"));
            JtxtNombres.setText(resultadoBusqueda.getString("nombre"));
            }
            while(resultadoBusquedaEstado.next()){
            
            if(resultadoBusquedaEstado.getBoolean("estado")){
            JtxtEstadoEstudiante.setText("Alta");
            
            }else{
            JtxtEstadoEstudiante.setText("Baja");
            }
            
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ventanaDarDeAlta_Baja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JbtnBuscarActionPerformed

    private void JbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnGuardarActionPerformed
        // TODO add your handling code here:
        admin.modificarEstadoEstudiante(JtxtCarnet.getText(),this.JcomboNuevoEstado.getSelectedItem().toString(),this.JtextAMotivoDeCambio.getText());
        
    }//GEN-LAST:event_JbtnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaDarDeAlta_Baja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaDarDeAlta_Baja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaDarDeAlta_Baja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaDarDeAlta_Baja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ventanaDarDeAlta_Baja().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnBuscar;
    private javax.swing.JButton JbtnGuardar;
    private javax.swing.JButton JbtnSalir;
    private javax.swing.JComboBox JcomboNuevoEstado;
    private javax.swing.JLabel JlblAppellidos;
    private javax.swing.JLabel JlblCarnet;
    private javax.swing.JLabel JlblEstadoEstudiante;
    private javax.swing.JLabel JlblImagen;
    private javax.swing.JLabel JlblMotivo;
    private javax.swing.JLabel JlblNombres;
    private javax.swing.JLabel JlblNuevoEstado;
    private javax.swing.JTextArea JtextAMotivoDeCambio;
    private javax.swing.JTextField JtxtApellidos;
    private javax.swing.JTextField JtxtCarnet;
    private javax.swing.JTextField JtxtEstadoEstudiante;
    private javax.swing.JTextField JtxtNombres;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
