/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotecaprogra3;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ph
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public ImageIcon icono =new ImageIcon("imagenesDeFormularios/library.png");
    //estas son todas las ventanas ke se pueden hacer visibles dependiendo si no estan abiertas
    private VentanaBuscarLibros ventanaBuscarLI=new VentanaBuscarLibros();
    private VentanaRegistrar Registro=new VentanaRegistrar();
    private ventanaDarDeAlta_Baja darDeAlta_Baja=new ventanaDarDeAlta_Baja();
    private ventanaAgregarEstudiante AgregarEstudiante=new ventanaAgregarEstudiante();
    private ventanaBuscarEstudiante buscarEstudiante=new ventanaBuscarEstudiante();
    private VentanaFichaDePrestamo vtFicha=new VentanaFichaDePrestamo();
    private ventanaRegistrarPrestamo prestamo=new ventanaRegistrarPrestamo();
    private ventanaRegistrarDevolucion devolucion=new ventanaRegistrarDevolucion();
    
    public VentanaPrincipal() {
        initComponents();
        ventanaBuscarLI.setVisible(true);
        PanelContenedor.add(ventanaBuscarLI);
          try {
           ventanaBuscarLI.setSelected(true);
        } catch (PropertyVetoException ex) {
         
        }
       bloquer(false,1);
        this.setIconImage(icono.getImage());
        this.setMinimumSize(new Dimension(400, 400));
        this.setLocation(50, 50);
       this.ElementoSalirSesion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JDesktopPane();
        BarraDeMenu = new javax.swing.JMenuBar();
        MenuIniciar = new javax.swing.JMenu();
        ElementoIniciarSecion = new javax.swing.JMenuItem();
        ElementoSalirSesion = new javax.swing.JMenuItem();
        MenuLibros = new javax.swing.JMenu();
        ElementoBuscarLibro = new javax.swing.JMenuItem();
        ElementoCargarLibros = new javax.swing.JMenuItem();
        MenuPrestamo = new javax.swing.JMenu();
        ElementoFichaDePRestamo = new javax.swing.JMenuItem();
        ElementoRegistrarPrestamo = new javax.swing.JMenuItem();
        ElementoRegistrarDevolucion = new javax.swing.JMenuItem();
        MenuEstudiantes = new javax.swing.JMenu();
        ElementoAgregarEstudiante = new javax.swing.JMenuItem();
        ElementoDarDeAlta = new javax.swing.JMenuItem();
        ElementoBuscarEstudiante = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        ElementoGenerarReportes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Login.png"))); // NOI18N
        MenuIniciar.setText("Sesion");
        MenuIniciar.setName("MenuIniciar");

        ElementoIniciarSecion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loginUsers.png"))); // NOI18N
        ElementoIniciarSecion.setText("Iniciar Sesion");
        ElementoIniciarSecion.setName("ElementoIniciarSecion");
        ElementoIniciarSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElementoIniciarSecionActionPerformed(evt);
            }
        });
        MenuIniciar.add(ElementoIniciarSecion);

        ElementoSalirSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        ElementoSalirSesion.setText("Cerrar Sesion");
        ElementoSalirSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElementoSalirSesionActionPerformed(evt);
            }
        });
        MenuIniciar.add(ElementoSalirSesion);

        BarraDeMenu.add(MenuIniciar);

        MenuLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/books.png"))); // NOI18N
        MenuLibros.setText("Libros");
        MenuLibros.setName("MenuLibros");

        ElementoBuscarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search book.png"))); // NOI18N
        ElementoBuscarLibro.setText("Buscar Libros");
        ElementoBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElementoBuscarLibroActionPerformed(evt);
            }
        });
        MenuLibros.add(ElementoBuscarLibro);

        ElementoCargarLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/load book.png"))); // NOI18N
        ElementoCargarLibros.setText("Cargar Libros");
        MenuLibros.add(ElementoCargarLibros);

        BarraDeMenu.add(MenuLibros);

        MenuPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prestamo.png"))); // NOI18N
        MenuPrestamo.setText("Prestamo");
        MenuPrestamo.setName("MenuPrestamo");

        ElementoFichaDePRestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print file.png"))); // NOI18N
        ElementoFichaDePRestamo.setText("Imprimir Ficha De Prestamo");
        ElementoFichaDePRestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElementoFichaDePRestamoActionPerformed(evt);
            }
        });
        MenuPrestamo.add(ElementoFichaDePRestamo);

        ElementoRegistrarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar prestamo.gif"))); // NOI18N
        ElementoRegistrarPrestamo.setText("Registrar Prestamo");
        ElementoRegistrarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElementoRegistrarPrestamoActionPerformed(evt);
            }
        });
        MenuPrestamo.add(ElementoRegistrarPrestamo);

        ElementoRegistrarDevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/return book.png"))); // NOI18N
        ElementoRegistrarDevolucion.setText("Registrar Devolucion");
        ElementoRegistrarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElementoRegistrarDevolucionActionPerformed(evt);
            }
        });
        MenuPrestamo.add(ElementoRegistrarDevolucion);

        BarraDeMenu.add(MenuPrestamo);

        MenuEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Student.png"))); // NOI18N
        MenuEstudiantes.setText("Estudiantes");
        MenuEstudiantes.setName("MenuEstudiantes");

        ElementoAgregarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add students.png"))); // NOI18N
        ElementoAgregarEstudiante.setText("Agregar Nuevo Estudiante");
        ElementoAgregarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElementoAgregarEstudianteActionPerformed(evt);
            }
        });
        MenuEstudiantes.add(ElementoAgregarEstudiante);

        ElementoDarDeAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dar de alta o baja.png"))); // NOI18N
        ElementoDarDeAlta.setText("Dar de Alta o Baja a Estudiante");
        ElementoDarDeAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElementoDarDeAltaActionPerformed(evt);
            }
        });
        MenuEstudiantes.add(ElementoDarDeAlta);

        ElementoBuscarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search person.png"))); // NOI18N
        ElementoBuscarEstudiante.setText("Buscar Estudiante");
        ElementoBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElementoBuscarEstudianteActionPerformed(evt);
            }
        });
        MenuEstudiantes.add(ElementoBuscarEstudiante);

        BarraDeMenu.add(MenuEstudiantes);

        MenuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/report.png"))); // NOI18N
        MenuReportes.setText("Reportes");
        MenuReportes.setName("MenuReportes");

        ElementoGenerarReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/create report.png"))); // NOI18N
        ElementoGenerarReportes.setText("Generar Reportes");
        ElementoGenerarReportes.setName("ElementoGenerarReportes");
        MenuReportes.add(ElementoGenerarReportes);

        BarraDeMenu.add(MenuReportes);

        setJMenuBar(BarraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ElementoIniciarSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElementoIniciarSecionActionPerformed

        if(!Registro.isVisible()){
        Registro.setVisible(true);
        Registro.setVtPrincipal(this);
        PanelContenedor.add(Registro);
        
          try {
            Registro.setSelected(true);
        } catch (PropertyVetoException ex) {
         
        }
        }else{
            JOptionPane.showMessageDialog(null,"ya esta habierta la ventana");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ElementoIniciarSecionActionPerformed

    private void ElementoAgregarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElementoAgregarEstudianteActionPerformed
        // TODO add your handling code here:
        if(!AgregarEstudiante.isVisible()){
        AgregarEstudiante.setVisible(true);
        AgregarEstudiante.pack();
        PanelContenedor.add(AgregarEstudiante);
          try {
           AgregarEstudiante.setSelected(true);
        } catch (PropertyVetoException ex) {
         
        }
        }else{
            JOptionPane.showMessageDialog(null, "Ya esta abierta esta ventana..");
        }
    }//GEN-LAST:event_ElementoAgregarEstudianteActionPerformed

    private void ElementoBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElementoBuscarLibroActionPerformed
        // TODO add your handling code here:
        if(!ventanaBuscarLI.isVisible()){
        ventanaBuscarLI.setVisible(true);
        PanelContenedor.add(ventanaBuscarLI);
          try {
            ventanaBuscarLI.setSelected(true);
        } catch (PropertyVetoException ex) {
         
        }
        }else{
            JOptionPane.showMessageDialog(null, "Ya esta abierta esta ventana..");
        }
    }//GEN-LAST:event_ElementoBuscarLibroActionPerformed

    private void ElementoFichaDePRestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElementoFichaDePRestamoActionPerformed
        // TODO add your handling code here:
        if(!vtFicha.isVisible()){
        vtFicha.setVisible(true);
        PanelContenedor.add(vtFicha);
          try {
           vtFicha.setSelected(true);
        } catch (PropertyVetoException ex) {
         
        }
        }else{
            JOptionPane.showMessageDialog(null, "Ya esta abierta esta ventana..");
        }
    }//GEN-LAST:event_ElementoFichaDePRestamoActionPerformed

    private void ElementoRegistrarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElementoRegistrarPrestamoActionPerformed
        // TODO add your handling code here:
        if(!prestamo.isVisible()){
        prestamo.setVisible(true);
        prestamo.setTitle("Prestamo Bibliotecario");
        PanelContenedor.add(prestamo);
          try {
            prestamo.setSelected(true);
        } catch (PropertyVetoException ex) {
         
        }
        }else{
            JOptionPane.showMessageDialog(null, "Ya esta abierta esta ventana..");
        }
        
    }//GEN-LAST:event_ElementoRegistrarPrestamoActionPerformed

    private void ElementoRegistrarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElementoRegistrarDevolucionActionPerformed
        // TODO add your handling code here:
        if(!devolucion.isVisible()){
        devolucion.setVisible(true);
        devolucion.pack();
        PanelContenedor.add(devolucion);
          try {
            devolucion.setSelected(true);
        } catch (PropertyVetoException ex) {
         
        }
        }else{
            JOptionPane.showMessageDialog(null, "Ya esta abierta esta ventana..");
        }
    }//GEN-LAST:event_ElementoRegistrarDevolucionActionPerformed

    private void ElementoDarDeAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElementoDarDeAltaActionPerformed
        // TODO add your handling code here:
        if(!darDeAlta_Baja.isVisible()){
        darDeAlta_Baja.setVisible(true);
        PanelContenedor.add(darDeAlta_Baja);
          try {
            darDeAlta_Baja.setSelected(true);
        } catch (PropertyVetoException ex) {
         
        }
        }else{
            JOptionPane.showMessageDialog(null, "Ya esta abierta esta ventana..");
        }
        
    }//GEN-LAST:event_ElementoDarDeAltaActionPerformed

    private void ElementoBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElementoBuscarEstudianteActionPerformed
        // TODO add your handling code here:
        if(!buscarEstudiante.isVisible()){
        buscarEstudiante.setVisible(true);
        PanelContenedor.add(buscarEstudiante);
          try {
           buscarEstudiante.setSelected(true);
        } catch (PropertyVetoException ex) {
         
        }
        }else{
        JOptionPane.showMessageDialog(null, "Ya esta abierta esta ventana..");    
        }
        
    }//GEN-LAST:event_ElementoBuscarEstudianteActionPerformed

    private void ElementoSalirSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElementoSalirSesionActionPerformed
        // TODO add your handling code here:
        bloquer(false, 1);
        this.ElementoSalirSesion.setEnabled(false);
    }//GEN-LAST:event_ElementoSalirSesionActionPerformed

    private void bloquer(boolean estado, int usuario){
        if (usuario==1){
           this.MenuEstudiantes.setEnabled(estado);
           this.MenuReportes.setEnabled(estado);
           this.ElementoCargarLibros.setEnabled(estado);
           this.ElementoRegistrarDevolucion.setEnabled(estado);
           this.ElementoRegistrarPrestamo.setEnabled(estado);
           this.ElementoIniciarSecion.setEnabled(true);
           this.ElementoSalirSesion.setEnabled(true);
        }
        
    }
    public void desbloquer(int usuario){
      if (usuario==1){
           this.MenuEstudiantes.setEnabled(true);
           this.MenuReportes.setEnabled(true);
           this.ElementoCargarLibros.setEnabled(true);
           this.ElementoRegistrarDevolucion.setEnabled(true);
           this.ElementoRegistrarPrestamo.setEnabled(true);
           this.ElementoIniciarSecion.setEnabled(false);
           this.ElementoSalirSesion.setEnabled(true);
           
        }  else if (usuario==2){
           this.MenuEstudiantes.setEnabled(true);
           this.ElementoBuscarEstudiante.setEnabled(false);
           this.ElementoCargarLibros.setEnabled(true);
           this.ElementoRegistrarDevolucion.setEnabled(true);
           this.ElementoRegistrarPrestamo.setEnabled(true); 
           this.ElementoIniciarSecion.setEnabled(false);
           
        } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraDeMenu;
    private javax.swing.JMenuItem ElementoAgregarEstudiante;
    private javax.swing.JMenuItem ElementoBuscarEstudiante;
    private javax.swing.JMenuItem ElementoBuscarLibro;
    private javax.swing.JMenuItem ElementoCargarLibros;
    private javax.swing.JMenuItem ElementoDarDeAlta;
    private javax.swing.JMenuItem ElementoFichaDePRestamo;
    private javax.swing.JMenuItem ElementoGenerarReportes;
    private javax.swing.JMenuItem ElementoIniciarSecion;
    private javax.swing.JMenuItem ElementoRegistrarDevolucion;
    private javax.swing.JMenuItem ElementoRegistrarPrestamo;
    private javax.swing.JMenuItem ElementoSalirSesion;
    private javax.swing.JMenu MenuEstudiantes;
    private javax.swing.JMenu MenuIniciar;
    private javax.swing.JMenu MenuLibros;
    private javax.swing.JMenu MenuPrestamo;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JDesktopPane PanelContenedor;
    // End of variables declaration//GEN-END:variables
}
