/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotecaprogra3;

import LogicaDeClases.AdministradorDatos;
import LogicaDeClases.Estudiante;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ph
 */
public class ventanaBuscarEstudiante extends javax.swing.JInternalFrame {
private AdministradorDatos admin=new AdministradorDatos();
private String rutaArchivo="";
private String nombreArchivo="";
private JFileChooser dlgFilechooser;
private  ImageIcon iconoEstudiante;
private Estudiante es;
    /**
     * Creates new form ventanaBuscarEstudiante
     */
     private ImageIcon icono=new ImageIcon("imagenesDeFormularios/search person.png");
    public ventanaBuscarEstudiante() {
        initComponents();
        this.setClosable(true);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setTitle(" Buscar Estudiante ");
        this.setIconifiable(true);
        this.setFrameIcon(icono);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        JlblCarnet = new javax.swing.JLabel();
        JlblNombre = new javax.swing.JLabel();
        JlblApellido = new javax.swing.JLabel();
        JlblEdad = new javax.swing.JLabel();
        JlblTelefono = new javax.swing.JLabel();
        JlblDireccion = new javax.swing.JLabel();
        JblImagen = new javax.swing.JLabel();
        JtxtCarnet = new javax.swing.JTextField();
        JtxtDireccion = new javax.swing.JTextField();
        JtxtTelefono = new javax.swing.JTextField();
        JtxtEdad = new javax.swing.JTextField();
        JtxtNombre = new javax.swing.JTextField();
        JtxtApellido = new javax.swing.JTextField();
        JbtnSalir = new javax.swing.JButton();
        JlblSexoo = new javax.swing.JLabel();
        JbtnBuscarEstudiante = new javax.swing.JButton();
        JtxtSexo = new javax.swing.JTextField();
        JbtnModificar = new javax.swing.JButton();
        pictureBoxImagenEstudiante = new PictureBox.PictureBox();
        JbtnGuardarCambios = new javax.swing.JButton();
        JbtnBuscarImagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JlblCarnet.setText("Carnet:");

        JlblNombre.setText("Nombre:");

        JlblApellido.setText("Apellido: ");

        JlblEdad.setText("Fecha Nacimiento:");

        JlblTelefono.setText("Telefono: ");

        JlblDireccion.setText("Dirección: ");

        JblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesGrandes/search person.png"))); // NOI18N

        JtxtDireccion.setEditable(false);

        JtxtTelefono.setEditable(false);

        JtxtEdad.setEditable(false);

        JtxtNombre.setEditable(false);

        JtxtApellido.setEditable(false);

        JbtnSalir.setText("Salir");
        JbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnSalirActionPerformed(evt);
            }
        });

        JlblSexoo.setText("Sexo: ");

        JbtnBuscarEstudiante.setText("Buscar Estudiante");
        JbtnBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuscarEstudianteActionPerformed(evt);
            }
        });

        JtxtSexo.setEditable(false);

        JbtnModificar.setText("Modificar Estudiante");
        JbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnModificarActionPerformed(evt);
            }
        });

        pictureBoxImagenEstudiante.setLayoutimg(PictureBox.PictureBox.imageLayout.StrechImage);

        javax.swing.GroupLayout pictureBoxImagenEstudianteLayout = new javax.swing.GroupLayout(pictureBoxImagenEstudiante);
        pictureBoxImagenEstudiante.setLayout(pictureBoxImagenEstudianteLayout);
        pictureBoxImagenEstudianteLayout.setHorizontalGroup(
            pictureBoxImagenEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );
        pictureBoxImagenEstudianteLayout.setVerticalGroup(
            pictureBoxImagenEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        JbtnGuardarCambios.setText("Guardar cambios");
        JbtnGuardarCambios.setEnabled(false);
        JbtnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnGuardarCambiosActionPerformed(evt);
            }
        });

        JbtnBuscarImagen.setText("Cambiar Imagen..");
        JbtnBuscarImagen.setEnabled(false);
        JbtnBuscarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuscarImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(JlblCarnet)
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JtxtCarnet)
                                .addGap(40, 40, 40))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JbtnBuscarEstudiante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addComponent(JbtnModificar)
                                .addGap(76, 76, 76))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(JblImagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pictureBoxImagenEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JlblDireccion)
                                    .addComponent(JlblSexoo))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(JtxtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(JtxtDireccion)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(JlblEdad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JlblTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JlblApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(30, 30, 30))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(JlblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JtxtApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                    .addComponent(JtxtEdad, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JtxtTelefono)
                                    .addComponent(JtxtNombre)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(JbtnGuardarCambios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)))
                        .addGap(44, 44, 44))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(JbtnBuscarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JblImagen)
                    .addComponent(pictureBoxImagenEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(JbtnBuscarImagen)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlblCarnet, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JtxtCarnet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnBuscarEstudiante)
                    .addComponent(JbtnModificar))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlblNombre)
                    .addComponent(JtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlblApellido)
                    .addComponent(JtxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlblEdad)
                    .addComponent(JtxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlblTelefono)
                    .addComponent(JtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlblDireccion)
                    .addComponent(JtxtDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlblSexoo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JtxtSexo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnGuardarCambios)
                    .addComponent(JbtnSalir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnModificarActionPerformed
        // TODO add your handling code here:
   desbloquerBloquer(true);
    }//GEN-LAST:event_JbtnModificarActionPerformed

    private void JbtnBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuscarEstudianteActionPerformed
        // TODO add your handling code here:
        desbloquerBloquer(false);
        ResultSet resultado;
        String id=this.JtxtCarnet.getText();
        resultado= admin.buscarEstudiante(id);
        try {
            while(resultado.next()){
            this.JtxtApellido.setText(resultado.getString("apellido"));
            this.JtxtDireccion.setText(resultado.getString("nombre"));
            this.JtxtEdad.setText(resultado.getString("fecha_nacimiento"));
            this.JtxtNombre.setText(resultado.getString("nombre"));
            this.JtxtSexo.setText(resultado.getString("sexo"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ventanaBuscarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
        ResultSet resultadoContacto;
        resultadoContacto=admin.buscarContacto(id);
        try {
            while(resultadoContacto.next()){
            this.JtxtTelefono.setText(resultadoContacto.getString("numero_telefono"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ventanaBuscarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
       
          iconoEstudiante =  admin.imagenEstudiante(id);
         
        this.pictureBoxImagenEstudiante.setIcono(iconoEstudiante);
        this.repaint();
    }//GEN-LAST:event_JbtnBuscarEstudianteActionPerformed

    private void JbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnSalirActionPerformed
        // TODO add your handling code here:
        this.doDefaultCloseAction();
    }//GEN-LAST:event_JbtnSalirActionPerformed

    private void JbtnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnGuardarCambiosActionPerformed
        // TODO add your handling code here:
        if(!this.JtxtNombre.getText().equalsIgnoreCase("")&& !this.JtxtApellido.getText().equalsIgnoreCase("")&& !this.JtxtCarnet.getText().equalsIgnoreCase("")&& !this.JtxtEdad.getText().equalsIgnoreCase("")&& !this.JtxtTelefono.getText().equalsIgnoreCase("")&& !this.JtxtDireccion.getText().equalsIgnoreCase("")&& !this.JtxtSexo.getText().equalsIgnoreCase("")){
        this.es=new Estudiante(this.JtxtNombre.getText(), this.JtxtApellido.getText(), this.JtxtCarnet.getText(), this.JtxtEdad.getText(), this.JtxtTelefono.getText(), this.JtxtDireccion.getText(), this.JtxtSexo.getText());
        admin.modificarEstudiante(es,this.rutaArchivo,this.nombreArchivo);
        }else{
        
        JOptionPane.showMessageDialog(null, "Existen campos que son obligatorios\n y no pueden estar vacios .-");
        }
        
        
        
    }//GEN-LAST:event_JbtnGuardarCambiosActionPerformed

    private void JbtnBuscarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuscarImagenActionPerformed
        // TODO add your handling code here:
        
        FileNameExtensionFilter filtro=new FileNameExtensionFilter("Archivos Permitidos: ",new String []{"png", "jpg", "jpeg", "gif", "bmp"});
        try{
        dlgFilechooser=new JFileChooser();
        dlgFilechooser.setFileFilter(filtro);
        int resultado;
        resultado = dlgFilechooser.showOpenDialog(this);
        if(resultado==JFileChooser.APPROVE_OPTION){
        this.nombreArchivo=dlgFilechooser.getSelectedFile().getName();
        this.rutaArchivo=dlgFilechooser.getSelectedFile().getAbsolutePath();
        this.pictureBoxImagenEstudiante.LoadImage(rutaArchivo);
        this.pictureBoxImagenEstudiante.repaint();
        
        }
        }catch(Exception ex){
        JOptionPane.showMessageDialog(this, "Error al intentar cargar la Imagen: "+ex.getMessage());
        }
    }//GEN-LAST:event_JbtnBuscarImagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaBuscarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaBuscarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaBuscarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaBuscarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new ventanaBuscarEstudiante().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JblImagen;
    private javax.swing.JButton JbtnBuscarEstudiante;
    private javax.swing.JButton JbtnBuscarImagen;
    private javax.swing.JButton JbtnGuardarCambios;
    private javax.swing.JButton JbtnModificar;
    private javax.swing.JButton JbtnSalir;
    private javax.swing.JLabel JlblApellido;
    private javax.swing.JLabel JlblCarnet;
    private javax.swing.JLabel JlblDireccion;
    private javax.swing.JLabel JlblEdad;
    private javax.swing.JLabel JlblNombre;
    private javax.swing.JLabel JlblSexoo;
    private javax.swing.JLabel JlblTelefono;
    private javax.swing.JTextField JtxtApellido;
    private javax.swing.JTextField JtxtCarnet;
    private javax.swing.JTextField JtxtDireccion;
    private javax.swing.JTextField JtxtEdad;
    private javax.swing.JTextField JtxtNombre;
    private javax.swing.JTextField JtxtSexo;
    private javax.swing.JTextField JtxtTelefono;
    private javax.swing.JPanel jPanel2;
    private PictureBox.PictureBox pictureBoxImagenEstudiante;
    // End of variables declaration//GEN-END:variables

    private void desbloquerBloquer(boolean estado) {
          this.JtxtApellido.setEditable(estado);
         this.JtxtNombre.setEditable(estado);
          this.JtxtSexo.setEditable(estado);
            this.JtxtDireccion.setEditable(estado);
             this.JtxtEdad.setEditable(estado);
             this.JtxtTelefono.setEditable(estado);
             this.JbtnGuardarCambios.setEnabled(estado);
             this.JbtnBuscarImagen.setEnabled(estado);
    }
}
