/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotecaprogra3;

import LogicaDeClases.AdministradorDatos;
import LogicaDeClases.Conexion;
import java.io.*;
import java.net.URI;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.tools.FileObject;

/**
 *
 * @author ph
 */
public class VentanaBuscarLibros extends javax.swing.JInternalFrame {

    private AdministradorDatos admin=new AdministradorDatos();
    private  DefaultTableModel modelo;
    
    /**
     * Creates new form VentanaBuscarLibros
     */
    
    
    private ImageIcon icono=new ImageIcon("imagenesDeFormularios/search book.png");
    public VentanaBuscarLibros() {
        initComponents();
        this.setResizable(true);
        this.setClosable(true);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setMaximizable(true);
        this.setTitle(" Buscar Libros ");
        this.setIconifiable(true);
        this.setFrameIcon(icono);
        this.modeloDeTablaLibros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JbtnBuscarLibros = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableListaDelibros = new javax.swing.JTable();
        JtxtBuscarLibros = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JbtnBuscarLibros.setText("Buscar");
        JbtnBuscarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuscarLibrosActionPerformed(evt);
            }
        });

        JtableListaDelibros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JtableListaDelibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JtableListaDelibros);

        JtxtBuscarLibros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtxtBuscarLibrosKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JtxtBuscarLibros)
                        .addGap(18, 18, 18)
                        .addComponent(JbtnBuscarLibros)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnBuscarLibros)
                    .addComponent(JtxtBuscarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnBuscarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuscarLibrosActionPerformed
   this.buscarAutoIncrementablelibros();
        
    }//GEN-LAST:event_JbtnBuscarLibrosActionPerformed

    private void JtxtBuscarLibrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtBuscarLibrosKeyReleased
       this.buscarAutoIncrementablelibros();
    }//GEN-LAST:event_JtxtBuscarLibrosKeyReleased

    private void modeloDeTablaLibros(){
   modelo=new DefaultTableModel();
    JtableListaDelibros.setModel(this.modelo);
    this.modelo.addColumn("ISBN");
    this.modelo.addColumn("Titulo");
    this.modelo.addColumn("Editorial");
    this.modelo.addColumn("Edición");
    this.modelo.addColumn("Clasificación");
    }
    
    private void buscarAutoIncrementablelibros(){
     try {
            // TODO add your handling code here:
         this.modeloDeTablaLibros();
           String BuscarTexto=JtxtBuscarLibros.getText();
            ResultSet resultadoBuscarLibros = admin.buscarLibros(BuscarTexto);
            Object[] datosLibro;
            while(resultadoBuscarLibros.next()){
           datosLibro=new Object[5];
            datosLibro[0]=resultadoBuscarLibros.getInt("ISBN");
            datosLibro[1]=resultadoBuscarLibros.getString("titulo");
            datosLibro[2]=resultadoBuscarLibros.getString("editorial");
            datosLibro[3]=resultadoBuscarLibros.getInt("edicion");
            datosLibro[4]=resultadoBuscarLibros.getString("clasificacion");
            this.modelo.addRow(datosLibro);
            }
            
                
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error al intentar cargar los libros: "+ex.getMessage());
        }
    
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VentanaBuscarLibros().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnBuscarLibros;
    private javax.swing.JTable JtableListaDelibros;
    private javax.swing.JTextField JtxtBuscarLibros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
